apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mongodb
  name: data-central-mongodb
spec:
  accessModes:
    - ReadWriteOnce
    
  storageClassName: "sc-cinder-delete"
  resources:
    requests:
      storage: "10Gi"