apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: grafana
  name: data-central-grafana
spec:
  accessModes:
    - ReadWriteOnce
    
  storageClassName: "sc-cinder-delete"
  resources:
    requests:
      storage: "2Gi"